import sys
import re

file_path = 'c:\\Putra\\Random\\ijazahaslijokowi\\app\\page.tsx'
content = open(file_path, 'r', encoding='utf-8').read()

VIRAL_ITEMS = [
  ("Odading Mang Oleh", "🍞", "Rasanya seperti menjadi Iron Man."),
  ("Es Teh Solo", "🥤", "Es teh tumpah ruah rasa khas Solo."),
  ("Seblak Prasmanan", "🥣", "Seblak njerit pedas mampus."),
  ("Ayam Geprek Bensin", "🍗", "Ayam geprek dibakar api."),
  ("Kopi Kenangan", "☕", "Kopi mantan manis tapi nyakitin."),
  ("Nasi Padang Karet Dua", "🍛", "Dibungkus, porsi kuli."),
  ("Indomie Telur Kornet", "🍜", "Makanan perbaikan gizi anak kos."),
  ("Mixue Ice Cream", "🍦", "Muncul di mana-mana di ruko kosong."),
  ("Basreng Pedas", "🍘", "Cemilan micin yang bikin nagih."),
  ("Cilor", "🍢", "Aci telor jajanan SD ter the best."),
  ("Makaroni Ngehe", "🍝", "Makaroni pedas gila."),
  ("Kue Pancong Lumer", "🥞", "Kue pancong setengah matang."),
  ("Tahu Bulat", "🍘", "Digoreng dadakan 500an."),
  ("Gorengan Mendoan", "🥟", "Tempe tipis digoreng tepung."),
  ("Martabak Manis", "🥞", "Kalori melimpah ruah manis pol."),
  ("Sosis Bakar", "🌭", "Sosis bratwurst jumbo dibakar bumbu."),
  ("Telur Gulung", "🍢", "Banyak minyaknya tapi tetep enak."),
  ("Pisang Nugget", "🍌", "Pisang goreng topping melimpah."),
  ("Cimol Bojot", "🥔", "Aci bumbu micin yang pedas."),
  ("Boba Brown Sugar", "🧋", "Minuman manis hits dari Taiwan."),
  ("Milo Kepal", "🍧", "Manis parah pekat coklatnya."),
  ("Teh Tarik", "🫖", "Teh manis ditarik sampe berbusa."),
  ("Ayam Kremes", "🍗", "Ayam kriuk kremes enak buat lauk."),
  ("Soto Betawi", "🥣", "Soto kuah susu yang gurih."),
  ("Sate Taichan", "🍢", "Sate ayam putih pedas."),
  ("Ropang", "🍞", "Roti bakar nongkrong tengah malam."),
  ("Mi Gacoan", "🍜", "Mi pedas level jutaan umat."),
  ("Ayam Penyet", "🍗", "Ayam dipenyet ke sambal."),
  ("Ayam Taliwang", "🍗", "Ayam pedas Lombok."),
  ("Rendang Sapi", "🥘", "Makanan terenak di dunia versi CNN."),
  ("Gulai Tambun", "🥣", "Gulai kuah gurih."),
  ("Es Doger", "🍧", "Es serut pacar cina manis."),
  ("Es Campur", "🍧", "Campur aduk segernya."),
  ("Sop Buntut", "🍲", "Sop kaldu sapi jernih."),
  ("Gado Gado", "🥗", "Salad khas Indonesia."),
  ("Pecel Lele", "🐟", "Makan malam sejuta umat."),
  ("Siomay Bandung", "🥟", "Siomay bumbu kacang legit."),
  ("Batagor", "🥟", "Bakso tahu goreng bandung."),
  ("Kerak Telor", "🍳", "Jajanan khas Jakarta Betawi."),
  ("Pempek Palembang", "🥟", "Pempek kapal selam kuah cuko."),
  ("Sate Ayam", "🍢", "Sate ayam bumbu kacang dan kecap."),
  ("Sate Padang", "🍢", "Sate kuah kuning pedas."),
  ("Gudeg Jogja", "🍛", "Nangka manis krecek pedas."),
  ("Nasi Liwet", "🍛", "Nasi gurih khas Sunda/Solo."),
  ("Tongseng", "🍲", "Tongseng kuah manis gurih."),
  ("Bakso Mercon", "🍲", "Bakso isi cabe rawit pedas."),
  ("Bakso Beranak", "🍲", "Bakso gede isinya bakso kecil."),
  ("Ayam Pop", "🍗", "Ayam rebus bumbu minang."),
  ("Cumi Cabe Garam", "🦑", "Cumi goreng asin pedas."),
  ("Pisang Goreng", "🍌", "Sajian wajib saat hujan manis."),
  ("Sayur Asem", "🥣", "Sayur kuah asem segar."),
  ("Rujak Cingur", "🥗", "Rujak buah dan cungur sapi."),
  ("Tahu Tek", "🥗", "Tahu goreng bumbu petis."),
  ("Pukis", "🥞", "Kue manis wangi pandan."),
  ("Onde-onde", "🍘", "Bulat goreng wijen isi kacang hijau."),
  ("Lemper", "🍙", "Ketan isi ayam dibungkus daun."),
  ("Nagasari", "🍙", "Kue pisang kukus santan."),
  ("Klepon", "🍡", "Bulat hijau isi gula merah lumer."),
  ("Bika Ambon", "🍰", "Kue kenyal bolong-bolong khas Medan."),
  ("Kastengel", "🧀", "Kue kering keju lebaran."),
  ("Nastar", "🍍", "Kue kering isi nanas."),
  ("Putri Salju", "❄", "Kue tabur gula halus."),
  ("Rengginang", "🍘", "Kerupuk beras ketan euy."),
  ("Kerupuk Putih", "🍘", "Teman makan apapun."),
  ("Pisang Molen", "🥟", "Pisang lilit adonan digoreng."),
  ("Risoles Mayo", "🥟", "Risol isi smoked beef telor mayo."),
  ("Pastel", "🥟", "Pastel isi sayur dan telur."),
  ("Tahu Gejrot", "🥣", "Tahu kuah coklat pedas bawang."),
  ("Es Puter", "🍧", "Es tradisional diputer."),
  ("Wedang Ronde", "🥣", "Jahe hangat bola ketan."),
  ("Wedang Jahe", "🍵", "Penghangat badan di malam dingin."),
  ("Kopi Joss", "☕", "Kopi dicemplungi arang panas."),
  ("Bubur Ayam", "🥣", "Diaduk atau tidak diaduk?"),
  ("Nasi Uduk", "🍛", "Sarapan khas warga Jakarta tiap pagi."),

  # Viral & memes
  ("Meme Fufufafa", "🤡", "Komentar kaskus legendaris."),
  ("Es Teh Jumbo", "🥤", "Porsi 3000 awet sampai malam."),
  ("Kocheng Oren", "🐈", "Ras kucing paling barbar di bumi."),
  ("Ibu Ibu Senam", "💃", "Dilarang melawan ibu-ibu senam sore."),
  ("Klakson Telolet", "🚌", "Hiburan anak pinggir jalan pantura."),
  ("Gitar Spanyol", "🎸", "Kata pujian atau alat musik?"),
  ("Lord Adi", "👑", "Mengendalikan waktu dan masakan."),
  ("Outfit Citayam", "🕶", "Skena SCBD Citayam Bojonggede Depok."),
  ("Pesawat Kertas", "🛩", "Bikin dari buku sekolah."),
  ("Koper Pejabat", "🧳", "Isinya apa ya mas bro?"),
  ("NMAX Arogan", "🏍", "Raja jalanan bersinar mulia."),
  ("Agya Ayla", "🚗", "Mobil lcgc beringas dan agresif."),
  ("Akun Palsu", "👤", "Hobby warganet menyamar."),
  ("Pinjol Galbay", "💸", "Dikejar debt collector."),
  ("Sandal Swallow", "🩴", "Gampang putus, sering hilang."),
  ("Sarung Bapak", "🧣", "Sering direbut bapak kedinginan."),
  ("Pejabat Korupsi", "🐀", "Tikus berdasi yang suka khilaf."),
  ("Uang Pelicin", "💵", "Amplop salam tempel biar lancar."),
  ("Ordal", "🤝", "Orang dalam penolong segalanya."),
  ("Kerja Rodi", "⛓", "Gaji UMR beban level CEO."),
  ("Tas Dior KW", "👜", "Beli di mangga dua miring harga."),
  ("HP Boba", "📱", "Kamera boba, idaman kaum gengsi."),
  ("BPJS Antre", "🏥", "Nunggu dokter lama dari nunggu peka."),
  ("Pak Ogah", "🚦", "Putar balik minta gopek."),
  ("Polisi Tidur", "🚧", "Nyundul sampai knalpot bolong."),
  ("Ojol Nyasar", "🛵", "Sesuai map kok mas, eh salah."),
  ("Anak Warnet", "🎮", "Mas, biling tambah sejam."),
  ("Keyboard Mekanik", "⌨", "Berisik sampai tetangga bangun."),
  ("Bocil Epep", "📱", "Ampun bang jago!"),
  ("Top Up Game", "💎", "Gaji abis modal gacha doang."),
  ("Minyak Angin", "🧴", "Obat segala penyakit orang tua."),
  ("Koyo Cabe", "🩹", "Atasi encok pegal linu abis narik."),
  ("Paramex", "💊", "Pusing mikirin negara ini."),
  ("Tolak Angin", "🧉", "Orang pintar minum tolak miskin."),
  ("Cuka Pempek", "🍾", "Bisa dipake nyiram hati yang panas."),
  ("Batu Akik", "🪨", "Dulu mahal sekarang buat timpuk maling."),
  ("Peliharaan Tuyul", "👽", "Maling duit ditaruh di bantal."),
  ("Dukun Santet", "🧙", "Guna-guna saingan bisnis warkop."),
  ("Pawang Hujan", "🌧", "Modal mangkok emas nahan badai."),
  ("CCTV Tilang", "📹", "Senyum, anda kena tilang ETLE!"),
  ("Kartu Keluarga", "📄", "Dipakai buat pinjol teman."),
  ("Surat Tilang", "📃", "Kertas biru pembawa sial."),
  ("Helm Bogo", "🪖", "Helm hits bonceng motor lucu."),
  ("Jas Hujan Kresek", "🧥", "Darurat yang penting gak basah."),
  ("Payung Terbalik", "☂", "Kena badai auto rusak ganti baru."),
  ("Jaket Ojol", "🧥", "Baju kebesaran penguasa jalan."),
  ("Knalpot Brong", "💨", "Berisik minta ditendang."),
  ("STNK Nunggak", "📑", "Pajak belum dibayar 5 tahun."),
  ("Tukang Parkir", "🙋", "Pas maju eh muncul gaib."),
  ("Tikar Piknik", "🧎", "Lebaran di kebun raya bawa tikar."),
  ("Galon Aqua", "💧", "Angkat pakai otot lumayan buat lengan."),
  ("Tabung Gas 3Kg", "🔋", "Senjata lempar terkuat."),
  ("Galon Le Minerale", "💧", "Ada manis manisnya gitu."),
  ("Rice Cooker Kos", "🍚", "Bisa masak nasi, mie, telur."),
  ("Kulkas Emak", "🧊", "Isinya bukan es krim tapi ikan beku."),
  ("Kaleng Khong Guan","🥫", "Ternyata isinya rengginang."),
  ("Panci Bolong", "🍳", "Gosong tapi masih dipake."),
  ("Spatula Penyet", "🥄", "Patah pas ayam nempel."),
  ("Baskom Pink", "🪣", "Serbaguna nyuci beras dsb euy."),
  ("Sabun Cair", "🧼", "Dikasih air kalau udah mau habis."),
  ("Odol Ditekan", "🪥", "Disilet bungkusnya kalau isinya macet."),
]

# Provide multiple to reach exactly 134. We have 141 in VIRAL_ITEMS
res = []
for i, item in enumerate(VIRAL_ITEMS[:134]):
    w = 15 - (i % 10)
    res.append(f'  {{ id: "viral_{i}", name: "{item[0]}", emoji: "{item[1]}", rarity: "umum", dropWeight: {w}, description: "{item[2]}" }},')

replacement = "const ITEMS: ItemDef[] = [\n" + \
"""  { id: "ikan",      name: "Ikan",                emoji: "🐟", rarity: "umum",   dropWeight: 30, description: "Ikan segar dari pasar pagi." },
  { id: "buku",      name: "Buku",                emoji: "📚", rarity: "umum",   dropWeight: 28, description: "Buku pelajaran penuh coretan." },
  { id: "pensil",    name: "Pensil",              emoji: "✏️", rarity: "umum",   dropWeight: 26, description: "Pensil 2B setengah terpakai." },
  { id: "susu",      name: "Susu",                emoji: "🥛", rarity: "umum",   dropWeight: 24, description: "Susu segar bergizi tinggi." },
  { id: "panci",     name: "Panci",               emoji: "🍳", rarity: "umum",   dropWeight: 22, description: "Panci masak anti lengket." },
  { id: "latolato",  name: "Lato Lato",           emoji: "⚫", rarity: "umum",   dropWeight: 20, description: "Mainan viral yang bikin berisik se-RT." },
  { id: "eskepalmilo", name: "Es Kepal Milo",     emoji: "🧇", rarity: "umum",   dropWeight: 18, description: "Es kepal Milo dingin dan manis, jajanan hits." },
  { id: "ompreng",   name: "Ompreng MBG",         emoji: "🍱", rarity: "langka", dropWeight: 10, description: "Ompreng MBG yang merupakan senjata terkuat WW3." },
  { id: "laptop",    name: "Laptop Chromebook",   emoji: "💻", rarity: "langka", dropWeight: 8,  description: "Chromebook tipis untuk kerja di mana saja." },
  { id: "kemeja",    name: "Kemeja Putih",        emoji: "👔", rarity: "langka", dropWeight: 7,  description: "Kemeja putih bersih tanpa noda." },
  { id: "peci",      name: "Peci",                emoji: "🎩", rarity: "langka", dropWeight: 6,  description: "Peci hitam khas, simbol kesopanan." },
  { id: "sarung",    name: "Sarung",              emoji: "🧣", rarity: "langka", dropWeight: 5,  description: "Sarung kotak-kotak serbaguna, bisa jadi apa saja." },
  { id: "sawit",     name: "Pohon Sawit",         emoji: "🌴", rarity: "epic",   dropWeight: 3,  description: "Pohon sawit penghasil minyak emas hijau." },
  { id: "kuda",      name: "Kuda",                emoji: "🐎", rarity: "epic",   dropWeight: 2,  description: "Kuda gagah berlari kencang di padang savana." },
  { id: "wayang",    name: "Dokumen Super Semar", emoji: "📜", rarity: "legend", dropWeight: 1,  description: "Manuskrip kuno berisikan perjanjian dewata, sangat langka!" },
  { id: "tembok",    name: "Tembok Ratapan",      emoji: "🧱", rarity: "legend", dropWeight: 1,  description: "Tembok keramat penuh doa dan air mata." },
""" + "\n".join(res) + "\n];"

pattern = re.compile(r'const ITEMS: ItemDef\[\] = \[.*?\];', re.DOTALL)
new_content = pattern.sub(replacement, content)

open(file_path, 'w', encoding='utf-8').write(new_content)
print("Finished adding items. Total length of array is", replacement.count("{ id: ") - 1, " Wait no, it's 150.")
